### ISSUE TITLE
confusion_matrix 下的addconfusion.data

### ISSUE THREAD

**Issue by SevenMpp** [Photooon/spell-correct#1]
您好，只是想请教您一下:
1、confusion_matrix文件夹下 .data格式文件。是依据什么生成的呢？？？？？
2、内部的vocab.txt 只是去重后的每个词吗？比如依据reuters.txt生成。

非常期待您的答复！！！

**Comment by Photooon** [comment]
1. Readme最下方的Ref里的最后一篇论文的Appendix给出了作者统计的Confusion Matrix，根据论文数据生成的
2. 是的，根据Reuters生成的

**Comment by SevenMpp** [comment]
谢谢，非常感谢您的回答！！！
